### ISSUE TITLE
Совместимость с opencart 2.*

### ISSUE THREAD

**Issue by neccospb** [hflabs/suggestions-opencart#2]
Планируется ли обновление вашего модуля до совместимой с актуальной opencart 2.0.3.1? Или есть альтернативные способы интеграции?

**Comment by algenon** [comment]
Мы не планируем развивать модуль. Есть платная альтернатива, поддерживает сторонний разработчик: http://liveopencart.ru/opencart-moduli-shablony/moduli/podskazki-dadata. Насчет поддержки 2.0 можно уточнить у него.
